version: '3.9'

services:
  db:
    name: barter-db
    restart: unless-stopped
    image: postgres:14
    env_file:
      - .env
    ports:
      - '${EXT_DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_DATABASE}']
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build: .
    name: barter-api
    command: sh /app/deployment/run.sh
    volumes:
      - .:/app
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      barter-db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - barter_network

volumes:
  db_data:

networks:
  barter_network:
    external: true
